package couriersystem;
/**
 *
 * @author jeerayuth
 */
import couriersystem.model.AdminPermission;
import couriersystem.model.DeliveryStaffPermission;
import couriersystem.model.GlobalConfig;
import couriersystem.model.LoggedInUser;
import couriersystem.model.ManagingStaffPermission;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Scanner;
import javax.swing.JOptionPane;
public class LoginForm extends javax.swing.JFrame {
    /**
     * Creates new form WindowB
     */
    public LoginForm() {
     
        initComponents();
        this.setTitle("User Login");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        chkView = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        txtPwd.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtUsername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        chkView.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        chkView.setText("View");
        chkView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkViewActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Role");

        comboRole.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Managing Staff", "Delivery Staff", "Admin" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPwd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(comboRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(chkView)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkView))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLogin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DeliveryPerson2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(35, 35, 35)
                .addComponent(btnCancel)
                .addGap(136, 136, 136))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnLogin))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = new String(txtPwd.getPassword());
        String role = comboRole.getSelectedItem().toString();
        boolean found = false;
        GlobalConfig.orderDateFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm aa");
        GlobalConfig.feedbackDateFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm aa");
        try{
            File myFile = new File(GlobalConfig.dbPath + "Account.txt");
            Scanner scanner = new Scanner(myFile);
            String row;
            // read every line in the file using a while loop
            // the while loop will detect whether the end of the file(EOF)
            // has been reached i.e. no more text in the next line
             // && !isBlank(temp = sc.nextLine())
            while(scanner.hasNext() && !found){
                row = scanner.nextLine();
                String [] values = row.split(",");

                  if (username.equals(values[1]) && password.equals(values[2]) && role.equals(values[3])){
                    found = true;
                      
                     if (values[4].equals("Inactive")){
                        JOptionPane.showMessageDialog(rootPane, "This account has been deactivated.", "Login Failed", JOptionPane.ERROR_MESSAGE);  
                        break;
                    }
                    
                    String userId = values[0];
                    username = values[1];
                    password = values[2];
                    role = values[3];
                    
                    if(role.equals("Managing Staff")){
                        String userDetails = findById(GlobalConfig.dbPath + "ManagingStaff.txt", userId);
                        String[] detailsArray = userDetails.split(",");
                        //set the name to a singleton, so that can access anywhere
                        LoggedInUser.getInstance().setUserId(detailsArray[0]);
                        LoggedInUser.getInstance().setName(detailsArray[1]);
                        LoggedInUser.getInstance().setRole(role);
                        LoggedInUser.getInstance().setPermission(new ManagingStaffPermission());
                        //Navigate to menu
                        new MenuManagingStaff().setVisible(true);
                    } else if(role.equals("Delivery Staff")){
                        String userDetails = findById(GlobalConfig.dbPath + "DeliveryStaff.txt", userId);
                        String[] detailsArray = userDetails.split(",");
                        //set the name to a singleton, so that can access anywhere
                        LoggedInUser.getInstance().setUserId(detailsArray[0]);
                        LoggedInUser.getInstance().setName(detailsArray[1]);
                        LoggedInUser.getInstance().setRole(role);
                        LoggedInUser.getInstance().setPermission(new DeliveryStaffPermission());
                        //Navigate to menu
                        new MenuDeliveryStaff().setVisible(true);
                    } else if(role.equals("Admin")){
                        String userDetails = findById(GlobalConfig.dbPath + "ManagingStaff.txt", userId);
                        String[] detailsArray = userDetails.split(",");
                        //set the name to a singleton, so that can access anywhere
                        LoggedInUser.getInstance().setUserId(detailsArray[0]);
                        LoggedInUser.getInstance().setName(detailsArray[1]);
                        LoggedInUser.getInstance().setRole(role);
                        LoggedInUser.getInstance().setPermission(new AdminPermission());
                        //Navigate to menu
                        new MenuAdmin().setVisible(true);
                    }
                    this.setVisible(false);//hide current window

                  }   
            }
            if(!found){
              JOptionPane.showMessageDialog(rootPane, "Incorrect Username, Password or Role. Please try again!", "Login Failed", JOptionPane.ERROR_MESSAGE);  
               comboRole.requestFocus();
            }
            scanner.close();
        }
        catch(IOException ex){
        
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    public String findById(String source, String id){
        Boolean found =  false;
        try{
            File myFile = new File(source);
            Scanner scanner = new Scanner(myFile);
            String row;
            // read every line in the file using a while loop
            // the while loop will detect whether the end of the file(EOF)
            // has been reached i.e. no more text in the next line
             // && !isBlank(temp = sc.nextLine())
            while(scanner.hasNext() && !found){
                row = scanner.nextLine();
                String [] values = row.split(",");

                  if (values[0].equals(id)){                     
                    found = true;
                    scanner.close();
                    return row;
                  }   
            }
            if(!found){
                scanner.close();
                return null;
            }
            scanner.close();
        }
        catch(IOException ex){
        
        }
        return null;
    }
    
    private boolean isBlank(String s){//check if no text
        return s == null || s.isEmpty();
    }  

    private void clearFields(){
        txtUsername.setText("");
        txtPwd.setText("");
        txtUsername.requestFocus();
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void chkViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkViewActionPerformed
        // TODO add your handling code here:
        if (chkView.isSelected()){
        txtPwd.setEchoChar((char)0);//unmask password        
        }
        else{
            txtPwd.setEchoChar('\u25cf');//back to default mask
        }        
    }//GEN-LAST:event_chkViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new javax.swing.ImageIcon(getClass().getResource("/com/jeerayuth/couriersystem/assets/DeliveryPerson2.png"))
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkView;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
