package couriersystem;


import couriersystem.model.Account;
import couriersystem.model.Address;
import couriersystem.model.GlobalConfig;
import couriersystem.model.LoggedInUser;
import couriersystem.model.Order;
import java.awt.event.KeyEvent;
import java.io.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author swee.kee
 */
public class OrderManagement extends javax.swing.JFrame {


    private String keyId;
    private ArrayList<JTextField> textFields;
    private ArrayList<Order> listOfOrders;
    private ArrayList<Order> searchedListOfOrders;
    ArrayList<String> deliveryStaffIDs;
    
    private Order orderTemp = new Order ();
    private String packageType;
    private String modeOfTransportation;
    private double weight;
    private double length;
    private double width;
    private double height;
    private Date orderDate;
    
    private boolean searched;

    /**
     * Creates new form AddStudentForm
     */
    public OrderManagement() {
        initComponents();
        //Validation: Check permission
        if (!LoggedInUser.getInstance().getPermission().allowOrderManagement()) {
            this.dispose();
        }
        setTitle("Order Management");
        setVisible(true);
        showOrderList();
        clearFields();
        
        //need this array for validation if it is empty
        textFields = new ArrayList<JTextField>();
        textFields.add(txtFieldWeight);
        textFields.add(txtFieldLength);
        textFields.add(txtFieldWidth);
        textFields.add(txtFieldHeight);
        textFields.add(txtFieldAddress1);
        textFields.add(txtFieldAddress2);
        textFields.add(txtFieldPostcode);
        textFields.add(txtFieldState);
        textFields.add(txtFieldCountry);
        textFields.add(txtFieldName);
        textFields.add(txtFieldContact);
        
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);

        ArrayList<Account> listOfAccounts = Account.getListOfAccounts();
        deliveryStaffIDs = new ArrayList<String>();
        for (Account acc : listOfAccounts){
            if (acc.getRole().equals("Delivery Staff") && acc.isActive()) {
                cbStaff.addItem(acc.getId());
                deliveryStaffIDs.add(acc.getId());
            }
        }
        //cbStaff = new JComboBox(deliveryStaffs.toArray());
    }
     
    public void showOrderList (){
        listOfOrders = Order.getListOfOrders();
        DefaultTableModel model =  (DefaultTableModel)ordersTable.getModel();
        model.setRowCount(0);
        String[] rowValues = new String[14];
        for (int i = 0; i < listOfOrders.size(); i++){
            rowValues[0] = listOfOrders.get(i).getPackageId();
            rowValues[1] = listOfOrders.get(i).getPackageType();
            rowValues[2] = String.format("%.2f",listOfOrders.get(i).getWeight());
            rowValues[3] = String.format("%.2f",listOfOrders.get(i).getLength());
            rowValues[4] = String.format("%.2f",listOfOrders.get(i).getWidth());
            rowValues[5] = String.format("%.2f",listOfOrders.get(i).getHeight());

            rowValues[6] = GlobalConfig.orderDateFormat.format(listOfOrders.get(i).getOrderDate());
            rowValues[7] = listOfOrders.get(i).getModeOfTransportation();
            rowValues[8] = listOfOrders.get(i).getShippingAddress().getFullAddress();
            
            rowValues[9] = listOfOrders.get(i).getOwner();
            rowValues[10] = listOfOrders.get(i).getOwnerContactNo();
            rowValues[11] = listOfOrders.get(i).getStatus();
            
            rowValues[12] = "RM " + String.format("%.2f",listOfOrders.get(i).calculatePrice());
            rowValues[13] = listOfOrders.get(i).getAssignedStaffID();
            model.addRow(rowValues);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageTypeGroup = new javax.swing.ButtonGroup();
        modeGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        txtSearchField = new javax.swing.JTextField();
        title1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFieldWeight = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFieldLength = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFieldWidth = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFieldHeight = new javax.swing.JTextField();
        rbParcel = new javax.swing.JRadioButton();
        rbDocument = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblOrderDate = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        rbLand = new javax.swing.JRadioButton();
        rbSea = new javax.swing.JRadioButton();
        rbAir = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        txtFieldAddress1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtFieldAddress2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtFieldPostcode = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtFieldState = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtFieldCountry = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtFieldContact = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtFieldName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblPackageID = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblPrice = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cbStaff = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel9.setText("Order Management");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Box.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel3.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 60));

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Package ID", "Package Type", "Weight (kg)", "Length (cm)", "Width (cm)", "Height (cm)", "Order Date", "Mode of Transport", "Shipping Address", "Owner", "Owner Contact No.", "Status", "Price", "Assigned Staff ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordersTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ordersTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel3);

        txtSearchField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchFieldKeyReleased(evt);
            }
        });

        title1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        title1.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(title1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(title1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Weight (kg)");

        txtFieldWeight.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFieldWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldWeightActionPerformed(evt);
            }
        });
        txtFieldWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldWeightKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldWeightKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("Length (cm)");

        txtFieldLength.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFieldLength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldLengthKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldLengthKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Width (cm)");

        txtFieldWidth.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFieldWidth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldWidthKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldWidthKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Height (cm)");

        txtFieldHeight.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFieldHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldHeightKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldHeightKeyTyped(evt);
            }
        });

        packageTypeGroup.add(rbParcel);
        rbParcel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbParcel.setText("Parcel");
        rbParcel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbParcelStateChanged(evt);
            }
        });

        packageTypeGroup.add(rbDocument);
        rbDocument.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbDocument.setText("Document");
        rbDocument.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbDocumentStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Package Type");

        lblOrderDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblOrderDate.setText("---");

        title.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        title.setText("Package Information");

        modeGroup.add(rbLand);
        rbLand.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbLand.setText("Through Land");
        rbLand.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbLandStateChanged(evt);
            }
        });

        modeGroup.add(rbSea);
        rbSea.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbSea.setText("Through Sea");
        rbSea.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbSeaStateChanged(evt);
            }
        });

        modeGroup.add(rbAir);
        rbAir.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbAir.setText("Through Air");
        rbAir.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbAirStateChanged(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setText("Address Line 1");

        txtFieldAddress1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setText("State");

        txtFieldAddress2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setText("Address Line 2");

        txtFieldPostcode.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFieldPostcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldPostcodeKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setText("Postcode");

        txtFieldState.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setText("Country");

        txtFieldCountry.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel17.setText("Order Information");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Order Date");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Mode Of Transportation");

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setText("Assign to");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel20.setText("Customer Information");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setText("Name");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("Contact No.");

        txtFieldContact.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFieldContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldContactKeyTyped(evt);
            }
        });

        btnBack1.setBackground(new java.awt.Color(204, 204, 204));
        btnBack1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnBack1.setMnemonic('C');
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(204, 255, 204));
        btnAdd.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAdd.setMnemonic('C');
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(204, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnUpdate.setMnemonic('C');
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtFieldName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Package ID");

        lblPackageID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPackageID.setText("---");

        btnClear.setBackground(new java.awt.Color(255, 255, 204));
        btnClear.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnClear.setMnemonic('C');
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 204, 204));
        btnDelete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnDelete.setMnemonic('C');
        btnDelete.setText("Cancel");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblStatus.setText("---");

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setText("Status");

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPrice.setFont(new java.awt.Font("Century Gothic", 1, 25)); // NOI18N
        lblPrice.setText("RM 0.00");

        title2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        title2.setText("Shipping Price");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(title2)
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel30.setText("Shipping Address");

        cbStaff.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title)
                            .addComponent(jLabel17)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel29))
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(rbLand)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbSea)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbAir))
                                            .addComponent(lblOrderDate)
                                            .addComponent(lblStatus)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel4))
                                        .addGap(131, 131, 131)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtFieldHeight)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(rbParcel)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rbDocument))
                                                .addComponent(txtFieldWeight, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtFieldLength, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtFieldWidth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblPackageID))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(49, 49, 49))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(147, 147, 147)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel28)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(236, 236, 236)
                                        .addComponent(cbStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel20))
                        .addGap(146, 180, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFieldAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel23))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(127, 127, 127)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFieldPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel30))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblPackageID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rbDocument)
                            .addComponent(rbParcel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtFieldLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtFieldWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtFieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblOrderDate))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rbSea)
                    .addComponent(rbLand)
                    .addComponent(rbAir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblStatus))
                .addGap(25, 25, 25)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldAddress1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtFieldAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtFieldPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldContact)
                    .addComponent(jLabel22))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cbStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack1)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnClear)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void ordersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersTableMouseClicked
        //when click on a record in the table
        clearFields();
        title.setText("Package Information");
        
        int i = ordersTable.getSelectedRow();
        TableModel model = ordersTable.getModel();
        Address address = null;
        if (!searched) {
            orderTemp = listOfOrders.get(i);
            address = listOfOrders.get(i).getShippingAddress();
        } else {
            orderTemp = searchedListOfOrders.get(i);
            address = searchedListOfOrders.get(i).getShippingAddress();
        }
        keyId = model.getValueAt(i,0).toString();
        lblPackageID.setText(model.getValueAt(i,0).toString());
        if (model.getValueAt(i,1).toString().equals("Parcel"))
            rbParcel.setSelected(true);
        else if (model.getValueAt(i,1).toString().equals("Document"))
            rbDocument.setSelected(true);
        txtFieldWeight.setText(model.getValueAt(i,2).toString());
        txtFieldLength.setText(model.getValueAt(i,3).toString());
        txtFieldWidth.setText(model.getValueAt(i,4).toString());
        txtFieldHeight.setText(model.getValueAt(i,5).toString());
        lblOrderDate.setText(model.getValueAt(i,6).toString());
        
        if (model.getValueAt(i,7).toString().equals("Land"))
            rbLand.setSelected(true);
        else if (model.getValueAt(i,7).toString().equals("Sea"))
            rbSea.setSelected(true);
        else if (model.getValueAt(i,7).toString().equals("Air"))
            rbAir.setSelected(true);
        if (address != null) {
            txtFieldAddress1.setText(address.getAddressLine1());
            txtFieldAddress2.setText(address.getAddressLine2());
            txtFieldPostcode.setText(address.getPostcode());
            txtFieldState.setText(address.getState());
            txtFieldCountry.setText(address.getCountry());
        }
        txtFieldName.setText(model.getValueAt(i,9).toString());
        txtFieldContact.setText(model.getValueAt(i,10).toString());
        lblStatus.setText(model.getValueAt(i,11).toString());
        lblPrice.setText(model.getValueAt(i,12).toString());
        
        btnAdd.setEnabled(false);
        if (model.getValueAt(i,11).toString().equals("Cancelled") || model.getValueAt(i,11).toString().equals("Delivered")) {
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            for (JTextField textfield : textFields) { 
                textfield.setEditable(false);
            }
            rbParcel.setEnabled(false);
            rbDocument.setEnabled(false);
            rbLand.setEnabled(false);
            rbSea.setEnabled(false);
            rbAir.setEnabled(false);
        } else {
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            for (JTextField textfield : textFields) { 
                textfield.setEditable(true);
            }
            rbParcel.setEnabled(true);
            rbDocument.setEnabled(true);
            rbLand.setEnabled(true);
            rbSea.setEnabled(true);
            rbAir.setEnabled(true);
        }
        
        try {
            orderDate = GlobalConfig.orderDateFormat.parse(model.getValueAt(i,6).toString());
        } catch (Exception ex) {
            orderDate = new Date();
        }
        
        cbStaff.setSelectedIndex(deliveryStaffIDs.indexOf(model.getValueAt(i,13).toString()));
    }//GEN-LAST:event_ordersTableMouseClicked

    private boolean validateForm(){
        //1. Empty Text field Validation
        //run a for loop over each text field and check if one of they is blank
        for (JTextField textfield : textFields) { 
            if (textfield.getText().isBlank()) {
                textfield.requestFocus();
                JOptionPane.showMessageDialog(rootPane, "Please ensure that all fields are entered.");
                return false;
            }
        }
        //2. validate package type
        if (rbParcel.isSelected() && !rbDocument.isSelected())
            packageType = "Parcel";
        else if (!rbParcel.isSelected() && rbDocument.isSelected())
            packageType = "Document";
        else {
            rbParcel.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Please choose a package type.");
            return false;
        }
        //3. validate mode of transpoort
        if (rbLand.isSelected() && !rbSea.isSelected() && !rbAir.isSelected())
            modeOfTransportation = "Land";
        else if (!rbLand.isSelected() && rbSea.isSelected() && !rbAir.isSelected())
            modeOfTransportation = "Sea";
        else if (!rbLand.isSelected() && !rbSea.isSelected() && rbAir.isSelected())
            modeOfTransportation = "Air";
        else {
            rbParcel.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Please choose a mode of transportation.");
            return false;
        }
        
        //4. validate if the entered value is a double or not
        try {
            weight = Double.parseDouble(txtFieldWeight.getText());
        } catch (NumberFormatException ex) {
           JOptionPane.showMessageDialog(rootPane, "Please enter digits only.");
           txtFieldWeight.requestFocus();
           return false;
        }
        try {
            length = Double.parseDouble(txtFieldLength.getText());
        } catch (NumberFormatException ex) {
           JOptionPane.showMessageDialog(rootPane, "Please enter digits only.");
           txtFieldLength.requestFocus();
           return false;
        }
        try {
            width = Double.parseDouble(txtFieldWidth.getText());
        } catch (NumberFormatException ex) {
           JOptionPane.showMessageDialog(rootPane, "Please enter digits only.");
           txtFieldWidth.requestFocus();
           return false;
        }
        try {
            height = Double.parseDouble(txtFieldHeight.getText());
        } catch (NumberFormatException ex) {
           JOptionPane.showMessageDialog(rootPane, "Please enter digits only.");
           txtFieldHeight.requestFocus();
           return false;
        }
        return true;
    }
    
    private Order setupOrder(String packageId, String status){
        Address shippingAddress = new Address (txtFieldAddress1.getText(), txtFieldAddress2.getText(), txtFieldPostcode.getText(), txtFieldState.getText(), txtFieldCountry.getText());
        Order order = new Order(
                packageId, 
                packageType,
                weight,
                length,
                width,
                height,
                orderDate,
                modeOfTransportation,
                shippingAddress,
                txtFieldName.getText(),
                txtFieldContact.getText(),
                status,
                cbStaff.getSelectedItem().toString()
        );
        return order;
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (validateForm() == false)
            return;
        
        //5. Assign current date and time
        orderDate = new Date();
        lblOrderDate.setText(GlobalConfig.orderDateFormat.format(orderDate));
        
        String packageId = "";
        
        //6. add number of record in ID_Tracker
        File curFile = new File(GlobalConfig.dbPath + "ID_Tracker.txt");
        File newFile = new File(GlobalConfig.dbPath + "temp.txt");
        String temp;
        try{
            FileWriter fw = new FileWriter(newFile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            Scanner sc = new Scanner(curFile);

            while(sc.hasNext())
            {
               temp = sc.nextLine();
               String [] tempArr = temp.split(",");
               if (tempArr[0].equals("Order")){
                    int currentNum = Integer.parseInt(tempArr[1]);
                    packageId = "PID" + currentNum;
                    currentNum += 1;
                    pw.println("Order," + Integer.toString(currentNum));
               } else {
                   pw.println(temp);
               }
            }
            sc.close(); //close scanner
            pw.flush(); 
            pw.close(); //close printwriter
            curFile.delete(); //delete current file
            File n = new File(GlobalConfig.dbPath + "ID_Tracker.txt");
            newFile.renameTo(n);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
        
        
        
        //7. Add order record
        try{
            // Create a new instance of Order class with the inputs
            Order order = setupOrder(packageId, "Processing");
            
            //Write to file
            FileWriter myFile = new FileWriter(GlobalConfig.dbPath + "Orders.txt",true);
            PrintWriter pw = new PrintWriter(myFile);
            pw.println(order.toOneLineString());
            pw.close();
            
            //Show Message Box
            JOptionPane.showMessageDialog(rootPane, "Order " + packageId + " created." , "Successful", JOptionPane.INFORMATION_MESSAGE);
         }
        catch (IOException ex){
            JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
        clearFields();  
            showOrderList();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (validateForm() == false)
            return;
        
        
        String packageId = keyId;
        
        File curFile = new File(GlobalConfig.dbPath + "Orders.txt");
        File newFile = new File(GlobalConfig.dbPath + "temp.txt");
        String row;
        try{
            FileWriter fw = new FileWriter(newFile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            Scanner sc = new Scanner(curFile);

            while(sc.hasNext())
            {
                row = sc.nextLine();
                String [] values = row.split("__");
                if(values[0].equals(packageId)){
                    Order order = setupOrder(packageId, lblStatus.getText());
                    pw.println(order.toOneLineString());
                } else {
                    pw.println(row);
                }
            }
            sc.close(); //close scanner
            pw.flush(); 
            pw.close(); //close printwriter
            curFile.delete(); //delete current file
            File n = new File(GlobalConfig.dbPath + "Orders.txt");
            newFile.renameTo(n); //rename temp to use oldfile name
            JOptionPane.showMessageDialog(rootPane, "Order " + packageId + " details updated!", "Update Successful", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception ex){
             JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
        clearFields();
        showOrderList();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String packageId = keyId;
        
        File curFile = new File(GlobalConfig.dbPath + "Orders.txt");
        File newFile = new File(GlobalConfig.dbPath + "temp.txt");
        String row;
        try{
            FileWriter fw = new FileWriter(newFile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            Scanner sc = new Scanner(curFile);

            while(sc.hasNext())
            {
                row = sc.nextLine();
                String [] values = row.split("__");
                if(values[0].equals(packageId)){
                    Order order = setupOrder(packageId, "Cancelled");
                    pw.println(order.toOneLineString());
                } else {
                    pw.println(row);
                }
            }
            sc.close(); //close scanner
            pw.flush(); 
            pw.close(); //close printwriter
            curFile.delete(); //delete current file
            File n = new File(GlobalConfig.dbPath + "Orders.txt");
            newFile.renameTo(n); //rename temp to use oldfile name
            JOptionPane.showMessageDialog(rootPane, "Order " + packageId + " cancelled.", "Successful", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception ex){
             JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
        clearFields();
        showOrderList();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchFieldKeyReleased
        try{

            String[] columnNames = {
                "Package ID","Package Type","Weight (kg)","Length (cm)","Width (cm)","Height (cm)",
                "Order Date", "Mode of Transportation", "Shipping Address", "Owner", "Owner Contact No.", " Status", "Price", "Assigned Staff ID"};
            DefaultTableModel model = (DefaultTableModel)ordersTable.getModel();
            model.setRowCount(0);
            ordersTable.revalidate();
            model.setColumnIdentifiers(columnNames);
            String keyword = txtSearchField.getText();
            
            String[] rowValues = new String[14];
            searchedListOfOrders = new ArrayList<Order>();
            searched = true;
            for (int i = 0; i < listOfOrders.size(); i++){
                rowValues[0] = listOfOrders.get(i).getPackageId();
                rowValues[1] = listOfOrders.get(i).getPackageType();
                rowValues[2] = String.format("%.2f",listOfOrders.get(i).getWeight());
                rowValues[3] = String.format("%.2f",listOfOrders.get(i).getLength());
                rowValues[4] = String.format("%.2f",listOfOrders.get(i).getWidth());
                rowValues[5] = String.format("%.2f",listOfOrders.get(i).getHeight());

                rowValues[6] = GlobalConfig.orderDateFormat.format(listOfOrders.get(i).getOrderDate());
                rowValues[7] = listOfOrders.get(i).getModeOfTransportation();
                rowValues[8] = listOfOrders.get(i).getShippingAddress().getFullAddress();

                rowValues[9] = listOfOrders.get(i).getOwner();
                rowValues[10] = listOfOrders.get(i).getOwnerContactNo();
                rowValues[11] = listOfOrders.get(i).getStatus();
                
                rowValues[12] = "RM " + String.format("%.2f",listOfOrders.get(i).calculatePrice());
                rowValues[13] = listOfOrders.get(i).getAssignedStaffID();
                
                for (String value : rowValues) {
                    if (value.contains(keyword)) {
                        model.addRow(rowValues);
                        searchedListOfOrders.add(listOfOrders.get(i));
                        break;
                    }
                }
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
    }//GEN-LAST:event_txtSearchFieldKeyReleased

    private void txtFieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldWeightActionPerformed
    
    private void txtFieldWeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldWeightKeyReleased
        if (txtFieldWeight.getText().isBlank()){
            orderTemp.setWeight(0);
            lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
        } else {
            try {
                orderTemp.setWeight(Double.parseDouble(txtFieldWeight.getText()));
                lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
            } catch (NumberFormatException ex) {
               return;
            }
        }
    }//GEN-LAST:event_txtFieldWeightKeyReleased

    private void txtFieldLengthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldLengthKeyReleased
        if (txtFieldLength.getText().isBlank()){
            orderTemp.setLength(0);
            lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
        } else {
            try {
                orderTemp.setLength(Double.parseDouble(txtFieldLength.getText()));
                lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
            } catch (NumberFormatException ex) {
               return;
            }
        }
    }//GEN-LAST:event_txtFieldLengthKeyReleased

    private void txtFieldWidthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldWidthKeyReleased
        if (txtFieldWidth.getText().isBlank()){
            orderTemp.setWidth(0);
            lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
        } else {
            try {
                orderTemp.setWidth(Double.parseDouble(txtFieldWidth.getText()));
                lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
            } catch (NumberFormatException ex) {
               return;
            }
        }
    }//GEN-LAST:event_txtFieldWidthKeyReleased

    private void txtFieldHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldHeightKeyReleased
        if (txtFieldHeight.getText().isBlank()){
            orderTemp.setHeight(0);
            lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
        } else {
            try {
                orderTemp.setHeight(Double.parseDouble(txtFieldHeight.getText()));
                lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
            } catch (NumberFormatException ex) {
               return;
            }
        }
    }//GEN-LAST:event_txtFieldHeightKeyReleased

    private void rbParcelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbParcelStateChanged
        if (rbParcel.isSelected() && !rbDocument.isSelected())
            orderTemp.setPackageType("Parcel");
        else if (!rbParcel.isSelected() && rbDocument.isSelected())
            orderTemp.setPackageType("Document");
        lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
    }//GEN-LAST:event_rbParcelStateChanged

    private void rbDocumentStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbDocumentStateChanged
        if (rbParcel.isSelected() && !rbDocument.isSelected())
            orderTemp.setPackageType("Parcel");
        else if (!rbParcel.isSelected() && rbDocument.isSelected())
            orderTemp.setPackageType("Document");
        lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
    }//GEN-LAST:event_rbDocumentStateChanged

    private void rbLandStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbLandStateChanged
        setModeTransportation();
        lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
    }//GEN-LAST:event_rbLandStateChanged

    private void rbSeaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbSeaStateChanged
        setModeTransportation();
        lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
    }//GEN-LAST:event_rbSeaStateChanged

    private void rbAirStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbAirStateChanged
        setModeTransportation();
        lblPrice.setText("RM " + String.format("%.2f",orderTemp.calculatePrice()));
    }//GEN-LAST:event_rbAirStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void txtFieldLengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldLengthKeyTyped
        char c = evt.getKeyChar();
        // check the key pressed by user
        if(!((Character.isDigit(c))|| c == KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )){           
            evt.consume(); // ignore the key
        }
    }//GEN-LAST:event_txtFieldLengthKeyTyped

    private void txtFieldWidthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldWidthKeyTyped
        char c = evt.getKeyChar();
        // check the key pressed by user
        if(!((Character.isDigit(c))|| c == KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )){           
            evt.consume(); // ignore the key
        }
    }//GEN-LAST:event_txtFieldWidthKeyTyped

    private void txtFieldWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldWeightKeyTyped
        char c = evt.getKeyChar();
        // check the key pressed by user
        if(!((Character.isDigit(c))|| c == KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )){           
            evt.consume(); // ignore the key
        }
    }//GEN-LAST:event_txtFieldWeightKeyTyped

    private void txtFieldHeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldHeightKeyTyped
        char c = evt.getKeyChar();
        // check the key pressed by user
        if(!((Character.isDigit(c))|| c == KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )){           
            evt.consume(); // ignore the key
        }
    }//GEN-LAST:event_txtFieldHeightKeyTyped

    private void txtFieldContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldContactKeyTyped
        char c = evt.getKeyChar();
        // check the key pressed by user
        if(!((Character.isDigit(c))|| c == KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )){           
            evt.consume(); // ignore the key
        }
    }//GEN-LAST:event_txtFieldContactKeyTyped

    private void txtFieldPostcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldPostcodeKeyTyped
        char c = evt.getKeyChar();
        // check the key pressed by user
        if(!((Character.isDigit(c))|| c == KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )){           
            evt.consume(); // ignore the key
        }
    }//GEN-LAST:event_txtFieldPostcodeKeyTyped
    private void setModeTransportation(){
        if (rbLand.isSelected() && !rbSea.isSelected() && !rbAir.isSelected())
            modeOfTransportation = "Land";
        else if (!rbLand.isSelected() && rbSea.isSelected() && !rbAir.isSelected())
            modeOfTransportation = "Sea";
        else if (!rbLand.isSelected() && !rbSea.isSelected() && rbAir.isSelected())
            modeOfTransportation = "Air";
        orderTemp.setModeOfTransportation(modeOfTransportation);
    }
    private void clearFields(){ 
        //clears the textfields
        lblPackageID.setText("---");
        packageTypeGroup.clearSelection();
        txtFieldWeight.setText("");
        txtFieldLength.setText("");
        txtFieldWidth.setText("");
        txtFieldHeight.setText("");
        lblOrderDate.setText("---");
        modeGroup.clearSelection();
        txtFieldAddress1.setText("");
        txtFieldAddress2.setText("");
        txtFieldPostcode.setText("");
        txtFieldState.setText("");
        txtFieldCountry.setText("");
        txtFieldName.setText("");
        txtFieldContact.setText("");
        lblStatus.setText("---");
        lblPrice.setText("RM 0.00");
        
        if (textFields != null){
            for (JTextField textfield : textFields) { 
                textfield.setEnabled(true);
                textfield.setEditable(true);
            }
        }
        rbParcel.setEnabled(true);
        rbDocument.setEnabled(true);
        rbLand.setEnabled(true);
        rbSea.setEnabled(true);
        rbAir.setEnabled(true);
        
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        title.setText("Create New Order");
        orderTemp = new Order();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblPackageID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStatus;
    private javax.swing.ButtonGroup modeGroup;
    private javax.swing.JTable ordersTable;
    private javax.swing.ButtonGroup packageTypeGroup;
    private javax.swing.JRadioButton rbAir;
    private javax.swing.JRadioButton rbDocument;
    private javax.swing.JRadioButton rbLand;
    private javax.swing.JRadioButton rbParcel;
    private javax.swing.JRadioButton rbSea;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JTextField txtFieldAddress1;
    private javax.swing.JTextField txtFieldAddress2;
    private javax.swing.JTextField txtFieldContact;
    private javax.swing.JTextField txtFieldCountry;
    private javax.swing.JTextField txtFieldHeight;
    private javax.swing.JTextField txtFieldLength;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JTextField txtFieldPostcode;
    private javax.swing.JTextField txtFieldState;
    private javax.swing.JTextField txtFieldWeight;
    private javax.swing.JTextField txtFieldWidth;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables
}
